name: Build and Push CRM Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Backend Image
        run: |
          docker build -t ghcr.io/heisenity/crm:latest ./backend

      - name: Push Docker Backend Image
        run: |
          docker push ghcr.io/heisenity/crm:latest

      - name: Build Docker Frontend Image
        run: |
          docker build -t ghcr.io/heisenity/crm:latest ./frontend

      - name: Push Docker Frontend Image
        run: |
          docker push ghcr.io/heisenity/crm:latest
